Introduce Testcontainers & Flyway
zalando-nakadi/fahrschein pull request #276
Opened 2022-01-17 15:24 UTC by otrosien

Adds Testcontainers to the Fahrschein-JDBC module. I'm not adding a re-usable docker-compose based setup yet, because the Integration Tests are so-far about testing writing cursors into a PostgreSQL and not yet about connecting to Nakadi. This will come in another PR.

Relates to https://github.com/zalando-nakadi/fahrschein/issues/271

2022-01-17 16:25 UTC, othon2000 commented
@otrosien about removing the DDL scripts from `src/main/resources:

If an application uses `JdbcCursorManager`, it needs to create the corresponding DB schema (and functions). 

I searched [all of Zalando](https://github.bus.zalan.do/search?q=JdbcCursorManager&type=code) and [all of github](https://github.com/search?q=JdbcCursorManager&type=code) but could not find any usage of it. [1]

However, if I were to find an usage, **I would expect the application to load the DDL scripts from the classpath** even though this is not documented anywhere.

That said, if we proceed with this PR, I recommend to move the scripts back and to document the usage of Flyway as part of using `fahrschein-jdbc`.

However, because of what I have mentioned in [1], does it even make sense to maintain this module? Why not removing it instead? Same goes for `RedisCursorManager`.

2022-01-18 08:55 UTC, otrosien commented
I'm afraid of breaking people's applications because of "too-much-magic". Suddenly Flyway finds new migrations on the classpath, and tries to execute them... Not really something I would expect when updating a dependency.

2022-01-18 08:56 UTC, otrosien commented
It's also nothing I found anywhere else. Flyway migrations should be in control of the application, which means we can point to them in the README, but people need to actively copy them over.

2022-01-19 16:59 UTC, othon2000 commented
> It's also nothing I found anywhere else. Flyway migrations should be in control of the application, which means we can point to them in the README, but people need to actively copy them over.

Sorry I was not very clear. I did not propose to embed flyway and do the migrations without the control of the user, but instead to **document how the user should do it**. Thus the migration scripts would need to be in the classpath (as they are today).

2022-01-24 10:12 UTC, othon2000 commented
:+1:

2022-03-07 14:23 UTC, othon2000 requested changes
The PR description also needs to be updated, regarding:

> Why have we been delivering the SQLs in src/main/resources, is that something genuinely relevant for our clients? I assume not, so I moved them into src/test/resources.

2022-03-07 15:41 UTC, otrosien commented on fahrschein-jdbc/src/test/java/org/zalando/fahrschein/jdbc/LocalPostgresConfiguration.java
> +        db.start();
I will add one for the nakadi-docker PR. A simple postgres (or a redis) is very easy and fast to spin up, which saves the hassle of having to think about dirty state.

2022-03-09 09:16 UTC, othon2000 commented
:+1:

2022-03-11 15:49 UTC, otrosien commented
👍

2022-03-11 16:13 UTC, merged