Add Nakadi-Docker based integration tests
zalando-nakadi/fahrschein pull request #300
Opened 2022-03-08 17:29 UTC by otrosien

Adds docker-compose based integration tests for the three httpclient integrations.

Closes #271 , builds ontop of #276 (to be rebased once merged)

Because of cyclic dependencies (`fahrschein -> fahrschein-http-simple -> fahrschein-test-support -> fahrschein`), I cannot put the `AbstractRequestFactoryTest` into `fahrschein-test-support`, but we could put the e2e-suite into a new module `fahrschein-e2e-test`, WDYT?

The metadata chages are also up to debate, I just realised there were some missing fields when running jackson with `FAIL_ON_UNKNOWN_PROPERTIES`.

TODO

* [x] Documentation (README)

2022-03-15 09:18 UTC, otrosien commented on pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
oops.

2022-03-15 11:04 UTC, othon2000 requested changes
Thanks for this.

I'm more in favor of having a new `fahrschein-e2e-test` module, as the test contents are not really  related to `fahrschein-example`.

2022-03-17 17:43 UTC, othon2000 commented on README.md
> +The `fahrschein-e2e-test` module has end-to-end tests using `docker-compose`. If you wish to leave the Docker containers running between tests, you can also bring up docker-compose manually using its
```suggestion
The `fahrschein-e2e-test` module has end-to-end tests using `docker-compose`. If you wish to leave the Docker containers running between tests, you can also bring up docker-compose manually using its [docker-compose.yaml](fahrschein-e2e-test/src/test/resources/docker-compose.yaml), before running the tests. In either case, you will need the port `8080` to be available for Nakadi to run.
```

2022-03-18 08:12 UTC, othon2000 approved these changes

2022-03-18 08:12 UTC, othon2000 commented
:+1:

2022-03-18 09:02 UTC, otrosien commented
👍

2022-03-18 09:02 UTC, merged