Adds ZStandard compression support
zalando-nakadi/fahrschein pull request #320
Opened 2022-04-13 13:33 UTC by otrosien

Adds ZStandard compression support, based on the same library that also Nakadi is using.

* Added compression support for both GZip and ZStandard
* Parametrized e2e-tests to check for all variations (NakadiClientE2ETest)
* Limits compression to `POST` requests, as [Nakadi only supports it for those](https://github.com/zalando/nakadi/blob/master/core-common/src/main/java/org/zalando/nakadi/util/CompressionBodyRequestFilter.java#L52). Luckily Fahrschein does not send any PATCH or PUT anyway. 

Closes #310 

## Tasks

* [x] Code implementation & unit tests
* [x] Cleanup of duplications in test code
* [x] End-to-end test 
* [x] README documentation

2022-04-28 13:34 UTC, othon2000 commented on fahrschein-http-api/src/main/java/org/zalando/fahrschein/http/api/ContentEncoding.java
> +    IDENTITY("identity"), GZIP("gzip"), ZSTD("zstd");
It's really elegant how adding a new `ContentEncoding` immediately makes it part of the `NakadiClientEnd2EndTest` for every existing http implementation. :smile:

2022-04-28 13:59 UTC, othon2000 requested changes
Minor changes requested in comments, otherwise looks good.

2022-04-28 13:59 UTC, othon2000 commented on fahrschein-http-api/src/main/java/org/zalando/fahrschein/http/api/ContentEncoding.java
> +            default:
I think it's better to also have a case for `IDENTITY` and throw an `UnsupportedOperationException` for `default`. It's more future-proof if we someday add new encoding.

2022-04-28 13:59 UTC, othon2000 commented on fahrschein-http-test-support/src/main/java/org/zalando/fahrschein/http/test/AbstractRequestFactoryTest.java
> +    public void testZStandardRequestBody() throws IOException {
Maybe extract the duplicated code from `testGzippedRequestBody` into a private method.

2022-04-28 13:59 UTC, othon2000 commented on fahrschein-http-test-support/src/main/java/org/zalando/fahrschein/http/test/AbstractRequestFactoryTest.java
> +        assertThat("content-encoding header", capturedArgument.getRequestHeaders().get("content-encoding"), equalTo(Arrays.asList("zstd")));
Better to use constants for every occurrence of `"content-encoding"`

2022-05-02 07:05 UTC, othon2000 approved these changes

2022-05-02 07:05 UTC, othon2000 commented
:+1:

2022-05-02 10:32 UTC, otrosien commented
👍

2022-05-02 10:32 UTC, merged